import { Photo, Video } from './models';

export const photoToDisplay: Photo[] = [
	{
		id: 'aa',
		url: 'https://i.imgur.com/t0x900S.jpg',
		creationDateTime: new Date('January 17, 2020 03:24:00'),
	},
	{
		id: 'ab',
		url: 'https://i.imgur.com/LonSqFi.png',
		creationDateTime: new Date('January 17, 2020 03:24:00'),
	},
	{
		id: 'ac',
		url: 'https://i.imgur.com/FklkvSE.jpg',
		creationDateTime: new Date('January 17, 2020 03:24:00'),
	},
	{
		id: 'ae',
		url: 'https://i.imgur.com/ZtRulbn.jpg',
		creationDateTime: new Date('January 17, 2020 03:24:00'),
	},
	{
		id: 'af',
		url: 'https://i.imgur.com/YD0MOmZ.jpg',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
	},
	{
		id: 'ag',
		url: 'https://i.imgur.com/6CZ2LLB.jpeg',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
	},
	{
		id: 'ah',
		url: 'https://i.imgur.com/HNLMF0P.jpg',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
	},
	{
		id: 'ak',
		url: 'https://i.imgur.com/0vb5W9m.jpg',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
	},
	{
		id: 'al',
		url: 'https://i.imgur.com/r3inDL8.jpg',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
	},
	{
		id: 'am',
		url: 'https://i.imgur.com/u0TXr08.jpeg',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
	},
	{
		id: 'an',
		url: 'https://i.imgur.com/N325EqP.jpg',
		creationDateTime: new Date('June 17, 2020 03:24:00'),
	},
	{
		id: 'ap',
		url: 'https://i.imgur.com/zpmoEhg.jpg',
		creationDateTime: new Date('June 17, 2020 03:24:00'),
	},
	{
		id: 'aa1',
		url: 'https://i.imgur.com/t0x900S.jpg',
		creationDateTime: new Date('January 17, 2018 03:24:00'),
	},
	{
		id: 'ab1',
		url: 'https://i.imgur.com/LonSqFi.png',
		creationDateTime: new Date('January 17, 2018 03:24:00'),
	},
	{
		id: 'ac1',
		url: 'https://i.imgur.com/FklkvSE.jpg',
		creationDateTime: new Date('January 17, 2018 03:24:00'),
	},
	{ id: 'ad1', url: 'https://i.imgur.com/lbLmdpg.jpg', creationDateTime: new Date('January 17, 2018 03:24:00') },
	{
		id: 'ae1',
		url: 'https://i.imgur.com/ZtRulbn.jpg',
		creationDateTime: new Date('January 17, 2018 03:24:00'),
	},
	{
		id: 'af12',
		url: 'https://i.imgur.com/YD0MOmZ.jpg',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
	},
	{
		id: 'ag12',
		url: 'https://i.imgur.com/6CZ2LLB.jpeg',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
	},
	{
		id: 'ah12',
		url: 'https://i.imgur.com/HNLMF0P.jpg',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
	},
	{
		id: 'ak12',
		url: 'https://i.imgur.com/0vb5W9m.jpg',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
	},
	{
		id: 'al12',
		url: 'https://i.imgur.com/r3inDL8.jpg',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
	},
	{
		id: 'am2',
		url: 'https://i.imgur.com/u0TXr08.jpeg',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
	},
	{
		id: 'an2',
		url: 'https://i.imgur.com/N325EqP.jpg',
		creationDateTime: new Date('June 17, 2019 03:24:00'),
	},
	{
		id: 'ap2',
		url: 'https://i.imgur.com/zpmoEhg.jpg',
		creationDateTime: new Date('June 17, 2019 03:24:00'),
	},
	{
		id: 'aa23',
		url: 'https://i.imgur.com/t0x900S.jpg',
		creationDateTime: new Date('January 17, 2017 03:24:00'),
	},
	{
		id: 'ab3',
		url: 'https://i.imgur.com/LonSqFi.png',
		creationDateTime: new Date('January 17, 2017 03:24:00'),
	},
	{
		id: 'ac3',
		url: 'https://i.imgur.com/FklkvSE.jpg',
		creationDateTime: new Date('January 17, 2017 03:24:00'),
	},
	{ id: 'ad3', url: 'https://i.imgur.com/lbLmdpg.jpg', creationDateTime: new Date('January 17, 2017 03:24:00') },
	{
		id: 'ae45',
		url: 'https://i.imgur.com/ZtRulbn.jpg',
		creationDateTime: new Date('January 17, 2017 03:24:00'),
	},
	{
		id: 'af5',
		url: 'https://i.imgur.com/YD0MOmZ.jpg',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
	},
	{
		id: 'ag5',
		url: 'https://i.imgur.com/6CZ2LLB.jpeg',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
	},
	{
		id: 'ah5',
		url: 'https://i.imgur.com/HNLMF0P.jpg',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
	},
	{
		id: 'ak5',
		url: 'https://i.imgur.com/0vb5W9m.jpg',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
	},
	{
		id: 'al5',
		url: 'https://i.imgur.com/r3inDL8.jpg',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
	},
	{
		id: 'am5',
		url: 'https://i.imgur.com/u0TXr08.jpeg',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
	},
	{
		id: 'an5',
		url: 'https://i.imgur.com/N325EqP.jpg',
		creationDateTime: new Date('June 17, 2018 03:24:00'),
	},
	{
		id: 'ap6',
		url: 'https://i.imgur.com/zpmoEhg.jpg',
		creationDateTime: new Date('June 17, 2018 03:24:00'),
	},
];

export const videoToDisplay: Video[] = [
	{
		id: 'aa1',
		previewImgUrl: 'https://i.imgur.com/t0x900S.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2020 03:24:00'),
		duration: 120,
	},
	{
		id: 'ab1',
		previewImgUrl: 'https://i.imgur.com/LonSqFi.png',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2020 03:24:00'),
		duration: 118,
	},
	{
		id: 'ac1',
		previewImgUrl: 'https://i.imgur.com/FklkvSE.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2020 03:24:00'),
		duration: 192,
	},
	{
		id: 'ad1',
		previewImgUrl: 'https://i.imgur.com/lbLmdpg.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2020 03:24:00'),
		duration: 131,
	},
	{
		id: 'ae1',
		previewImgUrl: 'https://i.imgur.com/ZtRulbn.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2020 03:24:00'),
		duration: 1256,
	},
	{
		id: 'af1',
		previewImgUrl: 'https://i.imgur.com/YD0MOmZ.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
		duration: 2287,
	},
	{
		id: 'ag1',
		previewImgUrl: 'https://i.imgur.com/6CZ2LLB.jpeg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
		duration: 287,
	},
	{
		id: 'ah1',
		previewImgUrl: 'https://i.imgur.com/HNLMF0P.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
		duration: 1687,
	},
	{
		id: 'ak1',
		previewImgUrl: 'https://i.imgur.com/0vb5W9m.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
		duration: 1023,
	},
	{
		id: 'al1',
		previewImgUrl: 'https://i.imgur.com/r3inDL8.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
		duration: 1753,
	},
	{
		id: 'am1',
		previewImgUrl: 'https://i.imgur.com/u0TXr08.jpeg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2020 03:24:00'),
		duration: 12569,
	},
	{
		id: 'an1',
		previewImgUrl: 'https://i.imgur.com/N325EqP.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('June 17, 2020 03:24:00'),
		duration: 56,
	},
	{
		id: 'ap1',
		previewImgUrl: 'https://i.imgur.com/zpmoEhg.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('June 17, 2020 03:24:00'),
		duration: 1,
	},
	{
		id: 'aa12',
		previewImgUrl: 'https://i.imgur.com/t0x900S.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2019 03:24:00'),
		duration: 120,
	},
	{
		id: 'ab12',
		previewImgUrl: 'https://i.imgur.com/LonSqFi.png',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2019 03:24:00'),
		duration: 118,
	},
	{
		id: 'ac12',
		previewImgUrl: 'https://i.imgur.com/FklkvSE.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2019 03:24:00'),
		duration: 192,
	},
	{
		id: 'ad12',
		previewImgUrl: 'https://i.imgur.com/lbLmdpg.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2019 03:24:00'),
		duration: 131,
	},
	{
		id: 'ae12',
		previewImgUrl: 'https://i.imgur.com/ZtRulbn.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2019 03:24:00'),
		duration: 1256,
	},
	{
		id: 'af12',
		previewImgUrl: 'https://i.imgur.com/YD0MOmZ.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
		duration: 2287,
	},
	{
		id: 'ag12',
		previewImgUrl: 'https://i.imgur.com/6CZ2LLB.jpeg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
		duration: 287,
	},
	{
		id: 'ah12',
		previewImgUrl: 'https://i.imgur.com/HNLMF0P.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
		duration: 1687,
	},
	{
		id: 'ak12',
		previewImgUrl: 'https://i.imgur.com/0vb5W9m.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
		duration: 1023,
	},
	{
		id: 'al12',
		previewImgUrl: 'https://i.imgur.com/r3inDL8.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
		duration: 1753,
	},
	{
		id: 'am12',
		previewImgUrl: 'https://i.imgur.com/u0TXr08.jpeg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2019 03:24:00'),
		duration: 12569,
	},
	{
		id: 'an12',
		previewImgUrl: 'https://i.imgur.com/N325EqP.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('June 17, 2019 03:24:00'),
		duration: 56,
	},
	{
		id: 'ap12',
		previewImgUrl: 'https://i.imgur.com/zpmoEhg.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('June 17, 2019 03:24:00'),
		duration: 1,
	},
	{
		id: 'aa13',
		previewImgUrl: 'https://i.imgur.com/t0x900S.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2018 03:24:00'),
		duration: 120,
	},
	{
		id: 'ab3',
		previewImgUrl: 'https://i.imgur.com/LonSqFi.png',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2018 03:24:00'),
		duration: 118,
	},
	{
		id: 'ac3',
		previewImgUrl: 'https://i.imgur.com/FklkvSE.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2018 03:24:00'),
		duration: 192,
	},
	{
		id: 'a3d',
		previewImgUrl: 'https://i.imgur.com/lbLmdpg.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2018 03:24:00'),
		duration: 131,
	},
	{
		id: 'ae3',
		previewImgUrl: 'https://i.imgur.com/ZtRulbn.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2018 03:24:00'),
		duration: 1256,
	},
	{
		id: 'af3',
		previewImgUrl: 'https://i.imgur.com/YD0MOmZ.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
		duration: 2287,
	},
	{
		id: 'ag3',
		previewImgUrl: 'https://i.imgur.com/6CZ2LLB.jpeg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
		duration: 287,
	},
	{
		id: 'ah3',
		previewImgUrl: 'https://i.imgur.com/HNLMF0P.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
		duration: 1687,
	},
	{
		id: 'ak3',
		previewImgUrl: 'https://i.imgur.com/0vb5W9m.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
		duration: 1023,
	},
	{
		id: 'al3',
		previewImgUrl: 'https://i.imgur.com/r3inDL8.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
		duration: 1753,
	},
	{
		id: 'am3',
		previewImgUrl: 'https://i.imgur.com/u0TXr08.jpeg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2018 03:24:00'),
		duration: 12569,
	},
	{
		id: 'an3',
		previewImgUrl: 'https://i.imgur.com/N325EqP.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('June 17, 2018 03:24:00'),
		duration: 56,
	},
	{
		id: 'ap3',
		previewImgUrl: 'https://i.imgur.com/zpmoEhg.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('June 17, 2018 03:24:00'),
		duration: 1,
	},
	{
		id: 'aa4',
		previewImgUrl: 'https://i.imgur.com/t0x900S.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2017 03:24:00'),
		duration: 120,
	},
	{
		id: 'ab4',
		previewImgUrl: 'https://i.imgur.com/LonSqFi.png',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2017 03:24:00'),
		duration: 118,
	},
	{
		id: 'ac4',
		previewImgUrl: 'https://i.imgur.com/FklkvSE.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2017 03:24:00'),
		duration: 192,
	},
	{
		id: 'ad4',
		previewImgUrl: 'https://i.imgur.com/lbLmdpg.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2017 03:24:00'),
		duration: 131,
	},
	{
		id: 'ae4',
		previewImgUrl: 'https://i.imgur.com/ZtRulbn.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('January 17, 2017 03:24:00'),
		duration: 1256,
	},
	{
		id: 'af4',
		previewImgUrl: 'https://i.imgur.com/YD0MOmZ.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2017 03:24:00'),
		duration: 2287,
	},
	{
		id: 'ag4',
		previewImgUrl: 'https://i.imgur.com/6CZ2LLB.jpeg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2017 03:24:00'),
		duration: 287,
	},
	{
		id: 'ah4',
		previewImgUrl: 'https://i.imgur.com/HNLMF0P.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2017 03:24:00'),
		duration: 1687,
	},
	{
		id: 'ak4',
		previewImgUrl: 'https://i.imgur.com/0vb5W9m.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2017 03:24:00'),
		duration: 1023,
	},
	{
		id: 'al4',
		previewImgUrl: 'https://i.imgur.com/r3inDL8.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2017 03:24:00'),
		duration: 1753,
	},
	{
		id: 'am4',
		previewImgUrl: 'https://i.imgur.com/u0TXr08.jpeg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('February 17, 2017 03:24:00'),
		duration: 12569,
	},
	{
		id: 'an4',
		previewImgUrl: 'https://i.imgur.com/N325EqP.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('June 17, 2017 03:24:00'),
		duration: 56,
	},
	{
		id: 'ap4',
		previewImgUrl: 'https://i.imgur.com/zpmoEhg.jpg',
		url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
		creationDateTime: new Date('June 17, 2017 03:24:00'),
		duration: 1,
	},
];
