import { CreateDraftMessage } from '@store/chats/features/create-draft-message/create-draft-message';
import { GetPossibleMembers } from '@store/chats/features/get-possible-members/get-possible-members';

import { AddUsersToGroupChat } from './features/add-users-to-group-chat/add-users-to-group-chat';
import { ChangeChatInfoOpened } from './features/change-chat-info-opened/change-chat-info-opened';
import { ChangeChatMutedStatus } from './features/change-chat-muted-status/change-chat-muted-status';
import { ChangeSelectedChat } from './features/change-selected-chat/change-selected-chat';
import { ClearChatHistory } from './features/clear-chat-history/clear-chat-history';
import { CopyMessages } from './features/copy-messages/copy-messages';
import { CreateGroupChat } from './features/create-group-chat/create-group-chat';
import { CreateMessage } from './features/create-message/create-message';
import { DeleteMessage } from './features/delete-message/delete-message';
import { EditGroupChat } from './features/edit-group-chat/edit-group-chat';
import { EditMessage } from './features/edit-message/edit-message';
import { ResetEditMessage } from './features/edit-message/reset-edit-message';
import { SubmitEditMessage } from './features/edit-message/submit-edit-message';
import { ForwardMessages } from './features/forward-messages/forward-messages';
import { GetAudioAttachments } from './features/get-audio-attachments/get-audio-attachments';
import { GetChatInfo } from './features/get-chat-info/get-chat-info';
import { GetChats } from './features/get-chats/get-chats';
import { GetGroupChatUsers } from './features/get-group-chat-users/get-group-chat-users';
import { GetMessages } from './features/get-messages/get-messages';
import { GetPhotoAttachments } from './features/get-photo-attachments/get-photo-attachments';
import { GetRawAttachments } from './features/get-raw-attachments/get-raw-attachments';
import { GetVideoAttachments } from './features/get-video-attachments/get-video-attachments';
import { GetVoiceAttachments } from './features/get-voice-attachments/get-voice-attachments';
import { LeaveGroupChat } from './features/leave-group-chat/leave-group-chat';
import { MarkChatAsRead } from './features/mark-chat-as-read/mark-chat-as-read';
import { MessageTyping } from './features/message-typing/message-typing';
import { RemoveAllAttachments } from './features/remove-attachment/remove-all-attachments';
import { RemoveAttachment } from './features/remove-attachment/remove-attachment';
import { RemoveChat } from './features/remove-chat/remove-chat';
import { RemoveUserFromGroupChat } from './features/remove-user-from-group-chat/remove-user-from-group-chat';
import { ReplyToMessage } from './features/reply-to-message/reply-to-message';
import { ResetReplyToMessage } from './features/reply-to-message/reset-reply-to-message';
import { ResetSearchChats } from './features/reset-search-chats/reset-search-chats';
import { ResetSelectedMessages } from './features/select-message/reset-selected-messages';
import { SelectMessage } from './features/select-message/select-message';
import { UploadAttachmentRequest } from './features/upload-attachment/upload-attachment-request';
import { UploadVoiceAttachment } from './features/upload-voice-attachment/upload-voice-attachment';
import { ChatMutedStatusChangedEventHandler } from './socket-events/chat-mute-status-changed/chat-mute-status-changed-event-handler';
import { DialogRemovedEventHandler } from './socket-events/dialog-removed/dialog-removed-event-handler';
import { MessageEditedEventHandler } from './socket-events/message-edited/message-edited-event-handler';
import { MessageReadEventHandler } from './socket-events/message-read/message-read-event-handler';
import { UserMessageTypingEventHandler } from './socket-events/message-typing/message-typing-event-handler';

// ChatActions
export const getChatsAction = GetChats.action;
export const getPhotoAttachmentsAction = GetPhotoAttachments.action;
export const getVideoAttachmentsAction = GetVideoAttachments.action;
export const getRawAttachmentsAction = GetRawAttachments.action;
export const getVoiceAttachmentsAction = GetVoiceAttachments.action;
export const getAudioAttachmentsAction = GetAudioAttachments.action;
export const getChatInfoAction = GetChatInfo.action;
export const changeSelectedChatAction = ChangeSelectedChat.action;
export const changeChatMutedStatusAction = ChangeChatMutedStatus.action;
export const createGroupChatAction = CreateGroupChat.action;
export const editGroupChatAction = EditGroupChat.action;
export const getGroupChatUsersAction = GetGroupChatUsers.action;
export const getPossibleChatMembersAction = GetPossibleMembers.action;
export const leaveGroupChatAction = LeaveGroupChat.action;
export const addUsersToGroupChatAction = AddUsersToGroupChat.action;
export const uploadAttachmentRequestAction = UploadAttachmentRequest.action;
export const removeAttachmentAction = RemoveAttachment.action;
export const markChatAsReadAction = MarkChatAsRead.action;
export const getMessagesAction = GetMessages.action;
export const createMessageAction = CreateMessage.action;
export const createDraftMessageAction = CreateDraftMessage.action;
export const messageTypingAction = MessageTyping.action;
export const deleteMessageAction = DeleteMessage.action;
export const selectMessageAction = SelectMessage.action;
export const resetSelectedMessagesAction = ResetSelectedMessages.action;
export const copyMessagesAction = CopyMessages.action;
export const replyToMessageAction = ReplyToMessage.action;
export const resetReplyToMessageAction = ResetReplyToMessage.action;
export const editMessageAction = EditMessage.action;
export const submitEditMessageAction = SubmitEditMessage.action;
export const resetEditMessageAction = ResetEditMessage.action;
export const clearChatHistoryAction = ClearChatHistory.action;
export const forwardMessagesAction = ForwardMessages.action;
export const changeChatInfoOpenedAction = ChangeChatInfoOpened.action;
export const removeAllAttachmentsAction = RemoveAllAttachments.action;
export const removeUserFromGroupChatAction = RemoveUserFromGroupChat.action;
export const resetSearchChatsAction = ResetSearchChats.action;
export const uploadVoiceAttachmentAction = UploadVoiceAttachment.action;

// socket-events

export const userMessageTypingEventHandlerAction = UserMessageTypingEventHandler.action;
export const chatMutedStatusChangedEventHandlerAction = ChatMutedStatusChangedEventHandler.action;
export const messageReadEventHandlerAction = MessageReadEventHandler.action;
export const messageEditedEventHandlerAction = MessageEditedEventHandler.action;
export const removeChatAction = RemoveChat.action;
export const dialogRemovedEventHandler = DialogRemovedEventHandler.action;
