export enum FriendsActionTypes {
  GET_FRIENDS = 'GET_FRIENDS',
  GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS',
  GET_FRIENDS_FAILURE = 'GET_FRIENDS_FAILURE',
  DELETE_FRIEND = 'DELETE_FRIEND',
  DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS',
  MARK_USER_AS_ADDED_TO_CONFERENCE = 'MARK_USER_AS_ADDED_TO_CONFERENCE',
  UNSET_SELECTED_USER_IDS_TO_ADD_INTO_CONFERENCE = 'UNSET_SELECTED_USER_IDS_TO_ADD_INTO_CONFERENCE',
  USER_STATUS_CHANGED_EVENT = 'USER_STATUS_CHANGED_EVENT'
}
