export const GET_FRIENDS = 'GET_FRIENDS';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const GET_FRIENDS_FAILURE = 'GET_FRIENDS_FAILURE';

export const DELETE_FRIEND = 'DELETE_FRIEND';
export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS';

export const MARK_USER_AS_ADDED_TO_CONFERENCE = 'MARK_USER_AS_ADDED_TO_CONFERENCE';
export const UNSET_SELECTED_USER_IDS_TO_ADD_INTO_CONFERENCE = 'UNSET_SELECTED_USER_IDS_TO_ADD_INTO_CONFERENCE';
