export const CHANGE_ONLINE_STATUS = 'CHANGE_ONLINE_STATUS';
export const CHANGE_INTERLOCUTOR_STATUS = 'CHANGE_INTERLOCUTOR_STATUS';
export const USER_STATUS_CHANGED_EVENT = 'USER_STATUS_CHANGED_EVENT';

export const UPDATE_MY_PROFILE_INFO = 'UPDATE_MY_PROFILE_INFO';
export const UPDATE_MY_AVATAR = 'UPDATE_MY_AVATAR';

export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
