ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: web.dev.kimbu.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: web.dev.kimbu.io-tls
     hosts:
       - web.dev.kimbu.io
