name: Build and Deploy
on:
  release:
    types: [published]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install project dependencies
        run: yarn

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
        
      - name: Define vars
        id: vars # Needed to reuse at 'with: steps.vars.outputs'
        shell: bash
        run: |
          # set tag version
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_MAIN_API: https://api.dev.kimbu.io
          envkey_REACT_APP_FILES_API: https://fs.dev.kimbu.io
          envkey_REACT_APP_WEBSOCKET_API: wss://ws.dev.kimbu.io/connection/websocket
          # set app version from tag
          envkey_REACT_APP_VERSION: ${{ steps.vars.outputs.tag }}
          file_name: .env

      - name: Build
        run: yarn run generate-conf && yarn build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
