name: Build
on:
  push:
    branches:
      - main
      - development
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_MAIN_API: https://api.dev.kimbu.io
        envkey_REACT_APP_FILES_API: https://fs.dev.kimbu.io
        envkey_REACT_APP_WEBSOCKET_API: wss://ws.dev.kimbu.io/connection/websocket
        file_name: .env

    - name: Build container image
      uses: docker/build-push-action@v2.7.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        repository: ${{ github.repository }}
        tags: latest
