name: ESLint pull request
on:
  pull_request:
    branches:
      - development

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install project dependencies
        run: yarn

      - name: Run ESLint
        run: yarn run lint
