name: Notify telegram group
on:
  push:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to telegram group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
